### ISSUE TITLE
Can the selenium-webdriver version be relaxed a bit?

### ISSUE THREAD

**Issue by oddui** [samccone/drool#22]
The selenium-webdriver version conflicts with my protractor ([2.5.1](https://github.com/angular/protractor/blob/2.5.1/package.json#L16)) setup and seems to cause the protractor tests to exit early.

So can the selenium-webdriver version be relaxed a bit? Thanks.

**Comment by samccone** [comment]
@oddui mind trying up the branch ^ and see if it works for you?

**Comment by oddui** [comment]
Thanks very much for that @samccone . I tried it but unfortunately it didn't work.

The node modules are installed like:

The protractor package has it's own node_modules folder with correct selenium-webdriver version(2.47.0). drool has a selenium-webdriver(2.46.1 on master, 2.48.2 on sjs/selenium-bump) next to it.

The protractor tests still exit early. Not too sure why, might be selenium-webdriver or protractor not work with node 5?

**Comment by samccone** [comment]
Updated to the latest selenium release
