### ISSUE TITLE
Getting different results with and without beforeAssert

### ISSUE THREAD

**Issue by praveensastry** [samccone/drool#37]
Hi, 

when the definition of action method is this, the node count is a match

```
action: () => {
        driver.findElement(drool.webdriver.By.css('.first-image-sixtile')).click();
        driver.findElement(drool.webdriver.By.css('.close-area')).click();
    }
```
but, when i change it to this, the node counts at assertion are different

```
action: () => {
        driver.findElement(drool.webdriver.By.css('.first-image-sixtile')).click();
    },
beforeAssert: () => {
        driver.findElement(drool.webdriver.By.css('.close-area')).click();
      }
```

Can you please explain this behavior?

**Comment by praveensastry** [comment]
@samccone can you please help me understand this?

**Comment by samccone** [comment]
Unfortunately without seeing your codebase and stepping through your application I am not going to be able to assist. 

Best of luck!
